Name change
geocortex/workflow-activities-arcfm pull request #18
Opened 2022-01-19 22:26 UTC by connerleverett

Change Geocortex -> VertiGIS Studio and apps.geocortex -> apps.vertigisstudio

2022-01-20 19:07 UTC, kenlyon requested changes

2022-01-20 19:07 UTC, kenlyon commented on README.md
> +This project contains activities for interacting with the [ArcFM Server REST API](https://resources.arcfmsolution.com/10.2.1d/ServerSDK/webframe.html#topic41788.html) in a [VertiGIS Studio Workflow](
Should the product name be changed?

2022-01-26 22:07 UTC, rcooney reviewed
The changes all look good. We just need to wait until https://apps.vertigisstudio.com/workflow/designer/ is live.

2022-02-16 16:59 UTC, kenlyon approved these changes

2022-02-16 17:03 UTC, merged